In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    l = len(layer_dims)            # number of layers in the network
    for i in range(1, l):
        parameters['W' + str(i)] = np.ones((layer_dims[i-1], layer_dims[i])) * 0.1
        parameters['b' + str(i)] = np.zeros((layer_dims[i], 1))
    return parameters

In [5]:
initialize_parameters([4, 3, 2])

{'W1': array([[0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1]]),
 'b1': array([[0.],
        [0.],
        [0.]]),
 'W2': array([[0.1, 0.1],
        [0.1, 0.1],
        [0.1, 0.1]]),
 'b2': array([[0.],
        [0.]])}

<h1>For Regression Problem</h1>

In [6]:
def linear_forward(A, W, b):
    Z = np.dot(W.T, A) + b
    return Z

In [7]:
def forward_propagation(X, parameters):
    A = X
    l = len(parameters) // 2  # number of layers in the network
    for i in range(1, l + 1):
        A_prev = A
        W = parameters['W' + str(i)]
        b = parameters['b' + str(i)]
        #print("A"+str(i-1)+":", A_prev)
        #print("W"+str(i)+":", W)
        #print("b"+str(i)+":", b)

        A = linear_forward(A_prev, W, b)
        #print("A"+str(i)+":", A)
        #print("*"*20)
    return A, A_prev

In [8]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2, 1)
Y = df[['lpa']].values[0][0]

In [9]:
Y

np.int64(4)

In [10]:
forward_propagation(X, initialize_parameters([2, 2, 1]))

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [11]:
def update_parameters(parameters, y, y_hat, A, x):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat) * A[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat) * A[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y-y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0] * x[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0] * x[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0] * x[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0] * x[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0])

In [12]:
parameters = initialize_parameters([2, 2, 1])
epochs =5

for i in range(epochs):
    print("Epoch:", i+1)
    print("="*30)

    Loss =[]

    for j in range(len(df)):
        x = df[['cgpa', 'profile_score']].values[j].reshape(2, 1)
        y = df[['lpa']].values[j][0]

        y_hat, A = forward_propagation(x, parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A, x)
        loss = (y_hat - y) ** 2
        Loss.append(loss)

    print("Epoch - ", i+1, " Loss - ", np.array(Loss).mean())

Epoch: 1
==============================
Epoch -  1  Loss -  26.28249792398698
Epoch: 2
==============================
Epoch -  2  Loss -  19.438253848220803
Epoch: 3
==============================
Epoch -  3  Loss -  10.139874435827522
Epoch: 4
==============================
Epoch -  4  Loss -  3.385561305106485
Epoch: 5
==============================
Epoch -  5  Loss -  1.3198454128484565

<h1>For Classification Problem</h1>

In [13]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa','profile_score','placed'])

In [14]:
df.head()

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [16]:
def linear_forward(A, W, b):
    Z = np.dot(W.T, A) + b
    A = sigmoid(Z)
    return A

In [17]:
def update_parameters(parameters, y, y_hat, A, x):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (y-y_hat) * A[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * (y-y_hat) * A[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * (y-y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (y-y_hat) * parameters['W2'][0][0] * A[0][0]*(1-A[0][0]) * x[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (y-y_hat) * parameters['W2'][0][0] * A[0][0]*(1-A[0][0]) * x[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * (y-y_hat) * parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * (y-y_hat) * parameters['W2'][1][0] * A[1][0]*(1-A[1][0]) * x[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (y-y_hat) * parameters['W2'][1][0] * A[1][0]*(1-A[1][0]) * x[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * (y-y_hat) * parameters['W2'][1][0])

In [18]:
parameters = initialize_parameters([2, 2, 1])
epochs = 50

for i in range(epochs):
    Loss=[]
    for j in range(len(df)):
        x = df[['cgpa', 'profile_score']].values[j].reshape(2, 1)
        y = df[['placed']].values[j][0]

        y_hat, A = forward_propagation(x, parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A, x)
        loss = (-y_hat * np.log(y_hat) - (1-y_hat) * np.log(1-y_hat))
        Loss.append(loss)
    print("Epoch - ", i+1, " Loss - ", np.array(Loss).mean())

Epoch -  1  Loss -  0.6898513521617208
Epoch -  2  Loss -  0.6898633424012985
Epoch -  3  Loss -  0.6898752823335771
Epoch -  4  Loss -  0.6898871721847558
Epoch -  5  Loss -  0.689899012179958
Epoch -  6  Loss -  0.6899108025432376
Epoch -  7  Loss -  0.6899225434975833
Epoch -  8  Loss -  0.6899342352649245
Epoch -  9  Loss -  0.6899458780661366
Epoch -  10  Loss -  0.689957472121046
Epoch -  11  Loss -  0.6899690176484354
Epoch -  12  Loss -  0.6899805148660496
Epoch -  13  Loss -  0.6899919639905998
Epoch -  14  Loss -  0.690003365237769
Epoch -  15  Loss -  0.6900147188222179
Epoch -  16  Loss -  0.6900260249575891
Epoch -  17  Loss -  0.6900372838565125
Epoch -  18  Loss -  0.6900484957306108
Epoch -  19  Loss -  0.6900596607905032

Epoch -  20  Loss -  0.6900707792458124
Epoch -  21  Loss -  0.6900818513051677
Epoch -  22  Loss -  0.6900928771762114
Epoch -  23  Loss -  0.6901038570656024
Epoch -  24  Loss -  0.6901147911790221
Epoch -  25  Loss -  0.6901256797211792
Epoch -  26  Loss -  0.6901365228958141
Epoch -  27  Loss -  0.6901473209057036
Epoch -  28  Loss -  0.6901580739526665
Epoch -  29  Loss -  0.6901687822375677
Epoch -  30  Loss -  0.6901794459603234
Epoch -  31  Loss -  0.6901900653199049
Epoch -  32  Loss -  0.6902006405143448
Epoch -  33  Loss -  0.6902111717407403
Epoch -  34  Loss -  0.6902216591952585
Epoch -  35  Loss -  0.6902321030731411
Epoch -  36  Loss -  0.6902425035687083
Epoch -  37  Loss -  0.6902528608753647
Epoch -  38  Loss -  0.6902631751856025
Epoch -  39  Loss -  0.6902734466910065
Epoch -  40  Loss -  0.6902836755822591
Epoch -  41  Loss -  0.690293862049144
Epoch -  42  Loss -  0.690304006280551
Epoch -  43  Loss -  0.6903141084644808
Epoch -  44  Loss -  0.6903241687880486
Epoch -  45  Loss -  0.6903341874374895
Epoch -  46  Loss -  0.6903441645981618
Epoch -  47  Loss -  0.690354100454552
Epoch -  48  Loss -  0.6903639951902792
Epoch -  49  Loss -  0.6903738489880988
Epoch -  50  Loss -  0.6903836620299078